### ISSUE TITLE
Error when posts have non-English characters

### ISSUE THREAD

**Issue by crbelaus** [elixir-tools/tableau#80]
I am trying to migrate my current website from Jekyll to Tableau and I've found a small bug when it tries to render a post that has non English characters in the title.

My post is called: `¿Qué es la programación funcional?` and when Tableau tries to render it from Markdown into HTML I get the following error:

```
19:25:13.837 [error] GenServer #PID<0.2170.0> terminating
** (File.Error) could not make directory (with -p) <<95, 115, 105, 116, 101, 47, 50, 48, 49, 54, 47, 48, 53, 47, 49, 48, 47, 194, 113, 117, 195, 45, 101, 115, 45, 108, 97, 45, 112, 114, 111, 103, 114, 97, 109, 97, 99, 105, 195, 110, 45, 102, 117, 110, 99, 105, 111, 110, 97, 108>>: unknown POSIX error: eilseq
    (elixir 1.15.5) lib/file.ex:319: File.mkdir_p!/1
    (tableau 0.15.3) lib/mix/tasks/tableau.build.ex:72: anonymous fn/5 in Mix.Tasks.Tableau.Build.run/1
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (tableau 0.15.3) lib/mix/tasks/tableau.build.ex:67: Mix.Tasks.Tableau.Build.run/1
    (mix 1.15.5) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (tableau 0.15.3) lib/tableau/router.ex:42: Tableau.Router.rerender/2
    (tableau 0.15.3) lib/tableau/router.ex:1: Tableau.Router.plug_builder_call/2
    (bandit 1.3.0) lib/bandit/pipeline.ex:103: Bandit.Pipeline.call_plug/2
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.104>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.3843209265.873988097.141771>, start_time: -576460114413566402, start_metadata: %{remote_address: {127, 0, 0, 1}, remote_port: 52013, telemetry_span_context: #Reference<0.3843209265.873988097.141771>, parent_telemetry_span_context: #Reference<0.3843209265.873988105.121747>}}}, %{opts: %{websocket: [], http_1: [], http_2: []}, plug: {Tableau.Router, []}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true, websocket_enabled: true}}
```

If I remove the opening question marks and the accents it seems to work just fine. The default permalink configuration that I am using is `"/:year/:month/:day/:title"`.

**Comment by crbelaus** [comment]
The workaround is to manually specify the permalink on each post that has problematic characters in the title.

**Comment by mhanberg** [comment]
Fixed in latest release
